// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppSettings {
    "TransparentMode": boolean;
    "ScanFolders": string[];
    "ScanFolderConfigs": ScanFolderConfig[];
    "Blacklist": string[];

    /** Creates a new AppSettings instance. */
    constructor($$source: Partial<AppSettings> = {}) {
        if (!("TransparentMode" in $$source)) {
            this["TransparentMode"] = false;
        }
        if (!("ScanFolders" in $$source)) {
            this["ScanFolders"] = [];
        }
        if (!("ScanFolderConfigs" in $$source)) {
            this["ScanFolderConfigs"] = [];
        }
        if (!("Blacklist" in $$source)) {
            this["Blacklist"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSettings {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ScanFolders" in $$parsedSource) {
            $$parsedSource["ScanFolders"] = $$createField1_0($$parsedSource["ScanFolders"]);
        }
        if ("ScanFolderConfigs" in $$parsedSource) {
            $$parsedSource["ScanFolderConfigs"] = $$createField2_0($$parsedSource["ScanFolderConfigs"]);
        }
        if ("Blacklist" in $$parsedSource) {
            $$parsedSource["Blacklist"] = $$createField3_0($$parsedSource["Blacklist"]);
        }
        return new AppSettings($$parsedSource as Partial<AppSettings>);
    }
}

export class ExtrasConfig {
    "EnableMangoHud": boolean;
    "EnableGamemode": boolean;
    "Lsfg": LsfgConfig;
    "Gamescope": GamescopeConfig;
    "Memory": MemoryConfig;

    /** Creates a new ExtrasConfig instance. */
    constructor($$source: Partial<ExtrasConfig> = {}) {
        if (!("EnableMangoHud" in $$source)) {
            this["EnableMangoHud"] = false;
        }
        if (!("EnableGamemode" in $$source)) {
            this["EnableGamemode"] = false;
        }
        if (!("Lsfg" in $$source)) {
            this["Lsfg"] = (new LsfgConfig());
        }
        if (!("Gamescope" in $$source)) {
            this["Gamescope"] = (new GamescopeConfig());
        }
        if (!("Memory" in $$source)) {
            this["Memory"] = (new MemoryConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExtrasConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ExtrasConfig {
        const $$createField2_0 = $$createType3;
        const $$createField3_0 = $$createType4;
        const $$createField4_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Lsfg" in $$parsedSource) {
            $$parsedSource["Lsfg"] = $$createField2_0($$parsedSource["Lsfg"]);
        }
        if ("Gamescope" in $$parsedSource) {
            $$parsedSource["Gamescope"] = $$createField3_0($$parsedSource["Gamescope"]);
        }
        if ("Memory" in $$parsedSource) {
            $$parsedSource["Memory"] = $$createField4_0($$parsedSource["Memory"]);
        }
        return new ExtrasConfig($$parsedSource as Partial<ExtrasConfig>);
    }
}

export class GameInfo {
    "name": string;
    "path": string;
    "icon": string;
    "config": LaunchOptions;
    "isRecent": boolean;
    "isAutoScanned": boolean;

    /** Creates a new GameInfo instance. */
    constructor($$source: Partial<GameInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }
        if (!("config" in $$source)) {
            this["config"] = (new LaunchOptions());
        }
        if (!("isRecent" in $$source)) {
            this["isRecent"] = false;
        }
        if (!("isAutoScanned" in $$source)) {
            this["isAutoScanned"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): GameInfo {
        const $$createField3_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField3_0($$parsedSource["config"]);
        }
        return new GameInfo($$parsedSource as Partial<GameInfo>);
    }
}

export class GamescopeConfig {
    "Enabled": boolean;

    /**
     * Nested width (-w)
     */
    "Width": string;

    /**
     * Nested height (-h)
     */
    "Height": string;

    /**
     * Output width (-W)
     */
    "OutputWidth": string;

    /**
     * Output height (-H)
     */
    "OutputHeight": string;

    /**
     * Nested refresh (-r)
     */
    "RefreshRate": string;

    /**
     * Frame limit (--framerate-limit)
     */
    "FramerateLimit": string;

    /**
     * "fullscreen", "borderless", "windowed"
     */
    "WindowMode": string;

    /**
     * auto, integer, fit, fill, stretch
     */
    "Scaler": string;

    /**
     * linear, nearest, fsr, nis, pixel
     */
    "Filter": string;

    /**
     * 0-20
     */
    "Sharpness": string;
    "HDR": boolean;
    "AdaptiveSync": boolean;
    "Mangoapp": boolean;
    "CustomArgs": string;

    /** Creates a new GamescopeConfig instance. */
    constructor($$source: Partial<GamescopeConfig> = {}) {
        if (!("Enabled" in $$source)) {
            this["Enabled"] = false;
        }
        if (!("Width" in $$source)) {
            this["Width"] = "";
        }
        if (!("Height" in $$source)) {
            this["Height"] = "";
        }
        if (!("OutputWidth" in $$source)) {
            this["OutputWidth"] = "";
        }
        if (!("OutputHeight" in $$source)) {
            this["OutputHeight"] = "";
        }
        if (!("RefreshRate" in $$source)) {
            this["RefreshRate"] = "";
        }
        if (!("FramerateLimit" in $$source)) {
            this["FramerateLimit"] = "";
        }
        if (!("WindowMode" in $$source)) {
            this["WindowMode"] = "";
        }
        if (!("Scaler" in $$source)) {
            this["Scaler"] = "";
        }
        if (!("Filter" in $$source)) {
            this["Filter"] = "";
        }
        if (!("Sharpness" in $$source)) {
            this["Sharpness"] = "";
        }
        if (!("HDR" in $$source)) {
            this["HDR"] = false;
        }
        if (!("AdaptiveSync" in $$source)) {
            this["AdaptiveSync"] = false;
        }
        if (!("Mangoapp" in $$source)) {
            this["Mangoapp"] = false;
        }
        if (!("CustomArgs" in $$source)) {
            this["CustomArgs"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GamescopeConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): GamescopeConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GamescopeConfig($$parsedSource as Partial<GamescopeConfig>);
    }
}

export class LaunchOptions {
    "ID": string;
    "Name": string;
    "LauncherPath": string;
    "GamePath": string;
    "UseGamePath": boolean;
    "PrefixPath": string;
    "ProtonPath": string;
    "UseCustomProton": boolean;
    "CustomArgs": string;
    "Extras": ExtrasConfig;

    /** Creates a new LaunchOptions instance. */
    constructor($$source: Partial<LaunchOptions> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("LauncherPath" in $$source)) {
            this["LauncherPath"] = "";
        }
        if (!("GamePath" in $$source)) {
            this["GamePath"] = "";
        }
        if (!("UseGamePath" in $$source)) {
            this["UseGamePath"] = false;
        }
        if (!("PrefixPath" in $$source)) {
            this["PrefixPath"] = "";
        }
        if (!("ProtonPath" in $$source)) {
            this["ProtonPath"] = "";
        }
        if (!("UseCustomProton" in $$source)) {
            this["UseCustomProton"] = false;
        }
        if (!("CustomArgs" in $$source)) {
            this["CustomArgs"] = "";
        }
        if (!("Extras" in $$source)) {
            this["Extras"] = (new ExtrasConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LaunchOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): LaunchOptions {
        const $$createField9_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Extras" in $$parsedSource) {
            $$parsedSource["Extras"] = $$createField9_0($$parsedSource["Extras"]);
        }
        return new LaunchOptions($$parsedSource as Partial<LaunchOptions>);
    }
}

export class LsfgConfig {
    "Enabled": boolean;
    "Multiplier": string;
    "PerfMode": boolean;
    "DllPath": string;
    "Gpu": string;
    "FlowScale": string;
    "Pacing": string;
    "AllowFp16": boolean;

    /** Creates a new LsfgConfig instance. */
    constructor($$source: Partial<LsfgConfig> = {}) {
        if (!("Enabled" in $$source)) {
            this["Enabled"] = false;
        }
        if (!("Multiplier" in $$source)) {
            this["Multiplier"] = "";
        }
        if (!("PerfMode" in $$source)) {
            this["PerfMode"] = false;
        }
        if (!("DllPath" in $$source)) {
            this["DllPath"] = "";
        }
        if (!("Gpu" in $$source)) {
            this["Gpu"] = "";
        }
        if (!("FlowScale" in $$source)) {
            this["FlowScale"] = "";
        }
        if (!("Pacing" in $$source)) {
            this["Pacing"] = "";
        }
        if (!("AllowFp16" in $$source)) {
            this["AllowFp16"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LsfgConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): LsfgConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LsfgConfig($$parsedSource as Partial<LsfgConfig>);
    }
}

export class LsfgProfileData {
    "name": string;
    "multiplier": number;
    "performanceMode": boolean;
    "gpu": string;
    "flowScale": number;
    "pacing": string;
    "dllPath": string;
    "allowFp16": boolean;

    /** Creates a new LsfgProfileData instance. */
    constructor($$source: Partial<LsfgProfileData> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("multiplier" in $$source)) {
            this["multiplier"] = 0;
        }
        if (!("performanceMode" in $$source)) {
            this["performanceMode"] = false;
        }
        if (!("gpu" in $$source)) {
            this["gpu"] = "";
        }
        if (!("flowScale" in $$source)) {
            this["flowScale"] = 0;
        }
        if (!("pacing" in $$source)) {
            this["pacing"] = "";
        }
        if (!("dllPath" in $$source)) {
            this["dllPath"] = "";
        }
        if (!("allowFp16" in $$source)) {
            this["allowFp16"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LsfgProfileData instance from a string or object.
     */
    static createFrom($$source: any = {}): LsfgProfileData {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LsfgProfileData($$parsedSource as Partial<LsfgProfileData>);
    }
}

export class MemoryConfig {
    "Enabled": boolean;
    "Value": string;

    /** Creates a new MemoryConfig instance. */
    constructor($$source: Partial<MemoryConfig> = {}) {
        if (!("Enabled" in $$source)) {
            this["Enabled"] = false;
        }
        if (!("Value" in $$source)) {
            this["Value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MemoryConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): MemoryConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MemoryConfig($$parsedSource as Partial<MemoryConfig>);
    }
}

export class PrefixConfigWithProton {
    "config": LaunchOptions;
    "protonDisplayName": string;
    "protonName": string;
    "protonPath": string;
    "protonIsSteam": boolean;

    /** Creates a new PrefixConfigWithProton instance. */
    constructor($$source: Partial<PrefixConfigWithProton> = {}) {
        if (!("config" in $$source)) {
            this["config"] = (new LaunchOptions());
        }
        if (!("protonDisplayName" in $$source)) {
            this["protonDisplayName"] = "";
        }
        if (!("protonName" in $$source)) {
            this["protonName"] = "";
        }
        if (!("protonPath" in $$source)) {
            this["protonPath"] = "";
        }
        if (!("protonIsSteam" in $$source)) {
            this["protonIsSteam"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PrefixConfigWithProton instance from a string or object.
     */
    static createFrom($$source: any = {}): PrefixConfigWithProton {
        const $$createField0_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField0_0($$parsedSource["config"]);
        }
        return new PrefixConfigWithProton($$parsedSource as Partial<PrefixConfigWithProton>);
    }
}

export class ProtonTool {
    "Name": string;
    "Path": string;
    "IsSteam": boolean;
    "DisplayName": string;

    /** Creates a new ProtonTool instance. */
    constructor($$source: Partial<ProtonTool> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("IsSteam" in $$source)) {
            this["IsSteam"] = false;
        }
        if (!("DisplayName" in $$source)) {
            this["DisplayName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProtonTool instance from a string or object.
     */
    static createFrom($$source: any = {}): ProtonTool {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProtonTool($$parsedSource as Partial<ProtonTool>);
    }
}

export class RunningSession {
    "pid": number;
    "gamePath": string;
    "gameName": string;

    /** Creates a new RunningSession instance. */
    constructor($$source: Partial<RunningSession> = {}) {
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }
        if (!("gamePath" in $$source)) {
            this["gamePath"] = "";
        }
        if (!("gameName" in $$source)) {
            this["gameName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunningSession instance from a string or object.
     */
    static createFrom($$source: any = {}): RunningSession {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RunningSession($$parsedSource as Partial<RunningSession>);
    }
}

export class ScanFolderConfig {
    "Path": string;
    "Depth": number;
    "ExcludeNames": string[];

    /** Creates a new ScanFolderConfig instance. */
    constructor($$source: Partial<ScanFolderConfig> = {}) {
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Depth" in $$source)) {
            this["Depth"] = 0;
        }
        if (!("ExcludeNames" in $$source)) {
            this["ExcludeNames"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScanFolderConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ScanFolderConfig {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ExcludeNames" in $$parsedSource) {
            $$parsedSource["ExcludeNames"] = $$createField2_0($$parsedSource["ExcludeNames"]);
        }
        return new ScanFolderConfig($$parsedSource as Partial<ScanFolderConfig>);
    }
}

export class ScannedFolderGroup {
    "folderPath": string;
    "folderName": string;
    "games": GameInfo[];

    /** Creates a new ScannedFolderGroup instance. */
    constructor($$source: Partial<ScannedFolderGroup> = {}) {
        if (!("folderPath" in $$source)) {
            this["folderPath"] = "";
        }
        if (!("folderName" in $$source)) {
            this["folderName"] = "";
        }
        if (!("games" in $$source)) {
            this["games"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScannedFolderGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): ScannedFolderGroup {
        const $$createField2_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("games" in $$parsedSource) {
            $$parsedSource["games"] = $$createField2_0($$parsedSource["games"]);
        }
        return new ScannedFolderGroup($$parsedSource as Partial<ScannedFolderGroup>);
    }
}

export class SystemInfo {
    "os": string;
    "kernel": string;
    "cpu": string;
    "gpu": string;
    "ram": string;
    "driver": string;

    /** Creates a new SystemInfo instance. */
    constructor($$source: Partial<SystemInfo> = {}) {
        if (!("os" in $$source)) {
            this["os"] = "";
        }
        if (!("kernel" in $$source)) {
            this["kernel"] = "";
        }
        if (!("cpu" in $$source)) {
            this["cpu"] = "";
        }
        if (!("gpu" in $$source)) {
            this["gpu"] = "";
        }
        if (!("ram" in $$source)) {
            this["ram"] = "";
        }
        if (!("driver" in $$source)) {
            this["driver"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SystemInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SystemInfo($$parsedSource as Partial<SystemInfo>);
    }
}

export class SystemToolsStatus {
    "hasGamescope": boolean;
    "hasMangoHud": boolean;
    "hasGameMode": boolean;
    "hasVulkanInfo": boolean;

    /** Creates a new SystemToolsStatus instance. */
    constructor($$source: Partial<SystemToolsStatus> = {}) {
        if (!("hasGamescope" in $$source)) {
            this["hasGamescope"] = false;
        }
        if (!("hasMangoHud" in $$source)) {
            this["hasMangoHud"] = false;
        }
        if (!("hasGameMode" in $$source)) {
            this["hasGameMode"] = false;
        }
        if (!("hasVulkanInfo" in $$source)) {
            this["hasVulkanInfo"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemToolsStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): SystemToolsStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SystemToolsStatus($$parsedSource as Partial<SystemToolsStatus>);
    }
}

export class SystemUsage {
    "cpu": string;
    "ram": string;
    "gpu": string;

    /** Creates a new SystemUsage instance. */
    constructor($$source: Partial<SystemUsage> = {}) {
        if (!("cpu" in $$source)) {
            this["cpu"] = "";
        }
        if (!("ram" in $$source)) {
            this["ram"] = "";
        }
        if (!("gpu" in $$source)) {
            this["gpu"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemUsage instance from a string or object.
     */
    static createFrom($$source: any = {}): SystemUsage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SystemUsage($$parsedSource as Partial<SystemUsage>);
    }
}

export class UtilsStatus {
    "isLsfgInstalled": boolean;
    "lsfgVersion": string;

    /** Creates a new UtilsStatus instance. */
    constructor($$source: Partial<UtilsStatus> = {}) {
        if (!("isLsfgInstalled" in $$source)) {
            this["isLsfgInstalled"] = false;
        }
        if (!("lsfgVersion" in $$source)) {
            this["lsfgVersion"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UtilsStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): UtilsStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UtilsStatus($$parsedSource as Partial<UtilsStatus>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ScanFolderConfig.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = LsfgConfig.createFrom;
const $$createType4 = GamescopeConfig.createFrom;
const $$createType5 = MemoryConfig.createFrom;
const $$createType6 = LaunchOptions.createFrom;
const $$createType7 = ExtrasConfig.createFrom;
const $$createType8 = GameInfo.createFrom;
const $$createType9 = $Create.Array($$createType8);
