// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class GitHubAsset {
    "name": string;
    "browser_download_url": string;
    "size": number;
    "content_type": string;

    /** Creates a new GitHubAsset instance. */
    constructor($$source: Partial<GitHubAsset> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("browser_download_url" in $$source)) {
            this["browser_download_url"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("content_type" in $$source)) {
            this["content_type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitHubAsset instance from a string or object.
     */
    static createFrom($$source: any = {}): GitHubAsset {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitHubAsset($$parsedSource as Partial<GitHubAsset>);
    }
}

export class GitHubRelease {
    "tag_name": string;
    "name": string;
    "published_at": string;
    "html_url": string;
    "assets": GitHubAsset[];

    /** Creates a new GitHubRelease instance. */
    constructor($$source: Partial<GitHubRelease> = {}) {
        if (!("tag_name" in $$source)) {
            this["tag_name"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("published_at" in $$source)) {
            this["published_at"] = "";
        }
        if (!("html_url" in $$source)) {
            this["html_url"] = "";
        }
        if (!("assets" in $$source)) {
            this["assets"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitHubRelease instance from a string or object.
     */
    static createFrom($$source: any = {}): GitHubRelease {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("assets" in $$parsedSource) {
            $$parsedSource["assets"] = $$createField4_0($$parsedSource["assets"]);
        }
        return new GitHubRelease($$parsedSource as Partial<GitHubRelease>);
    }
}

export class ProtonVariant {
    "ID": string;
    "Name": string;
    "Description": string;
    "RepoOwner": string;
    "RepoName": string;

    /** Creates a new ProtonVariant instance. */
    constructor($$source: Partial<ProtonVariant> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Description" in $$source)) {
            this["Description"] = "";
        }
        if (!("RepoOwner" in $$source)) {
            this["RepoOwner"] = "";
        }
        if (!("RepoName" in $$source)) {
            this["RepoName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProtonVariant instance from a string or object.
     */
    static createFrom($$source: any = {}): ProtonVariant {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProtonVariant($$parsedSource as Partial<ProtonVariant>);
    }
}

// Private type creation functions
const $$createType0 = GitHubAsset.createFrom;
const $$createType1 = $Create.Array($$createType0);
