BINARY_NAME=light-launcher
INSTANCE_BIN=light-launcher-instance
BIN_DIR=bin
DIST_DIR=dist
PROJECT_DIR=ui
WAILS_BIN=$(shell go env GOPATH)/bin/wails3

check:
	@echo "Checking Go code..."
	go vet ./...
	@echo "Checking Frontend code..."
	cd ui/frontend && bun run check

build-all:
	mkdir -p $(BIN_DIR)
	$(MAKE) build-instance
	$(MAKE) build-ui

build-instance:
	go build -o $(BIN_DIR)/$(INSTANCE_BIN) ./cmd/instance

build-ui:
	PATH="$(shell go env GOPATH)/bin:$(PATH)" $(WAILS_BIN) task build

package: build-instance
	PATH="$(shell go env GOPATH)/bin:$(PATH)" $(WAILS_BIN) task package
	cp bin/light-launcher* $(BIN_DIR)/

build: build-all
	rm -rf $(DIST_DIR)
	mkdir -p $(DIST_DIR)/linux/bin
	mkdir -p $(DIST_DIR)/linux/share/applications
	mkdir -p $(DIST_DIR)/linux/share/icons/hicolor/128x128/apps
	# Binaries
	cp $(BIN_DIR)/$(BINARY_NAME) $(DIST_DIR)/linux/bin/
	cp $(BIN_DIR)/$(INSTANCE_BIN) $(DIST_DIR)/linux/bin/
	# Desktop file (generated by Wails task)
	cp ui/build/linux/$(BINARY_NAME).desktop $(DIST_DIR)/linux/share/applications/
	# Icon
	cp ui/build/appicon.png $(DIST_DIR)/linux/share/icons/hicolor/128x128/apps/$(BINARY_NAME).png

generate-bindings:
	PATH="$(shell go env GOPATH)/bin:$(PATH)" $(WAILS_BIN) generate bindings -ts -d ui/frontend/bindings ./...

dev: build-instance
	PATH="$(shell go env GOPATH)/bin:$(PATH)" $(WAILS_BIN) task dev

start: build
	$(BIN_DIR)/$(BINARY_NAME)

clean:
	rm -rf $(BIN_DIR)
	rm -rf $(DIST_DIR)
	rm -rf $(PROJECT_DIR)/bin
	rm -rf $(PROJECT_DIR)/build/linux/appimage/build
